application: breakup09
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /purchase/.*
  script: purchase.py

- url: /admin/.*
  script: main.py
  login: admin
  
- url: .*
  script: main.py

  