application: breakup09
#application: easy-ebook-shop
version: 1 
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /admin/.*
  script: main.py
  login: admin

- url: /ignoreme/.*
  script: ignoreme.py
  login: admin
  
- url: .*
  script: main.py

  
